### ISSUE TITLE
Duke 3D GOG not getting randomized at all

### ISSUE THREAD

**Issue by workdowg** [Die4Ever/build-engine-randomizer#30]
Downloaded the newest eDuke3D and your latest randomizer. I only changed the randomize levels from your default. I select Randomizer in eDuke3D, start a new game and nothing changes. All enemies are right where I know and it doesn't randomizer even the levels. Here is my Randomizer.html (sorry it is pastebin...), https://pastebin.com/17hK986a .  I What is the trigger to get it to actually change the game?

**Comment by Die4Ever** [comment]
I will look into this tonight. It looks like you have the old Atomic Edition from GOG? Could you also share the eDuke32 log file? Also for now you could maybe try disabling the "Use Randomizer Folder" option and see if that works?

**Comment by Die4Ever** [comment]
could you send me your `eduke32.cfg` and `eduke32.log` files? The log file you should be able to just drag and drop into Github, the cfg file you could rename it to a txt file or share it any other way

**Comment by Die4Ever** [comment]
also if you could make a zip file of your Randomizer folder that could help, just so I can make sure that the files were randomized properly

**Comment by workdowg** [comment]
Will do once I'm home. Thanks for being on top of things!

**Comment by workdowg** [comment]
It still a no go. I disabled the randomizer folder setting...here are the log and cfg(txt now). I'll try a clean install and try Blood tomorrow. Long day at work today...

[eduke32.log](https://github.com/Die4Ever/build-engine-randomizer/files/10830298/eduke32.log)
[eduke32.txt](https://github.com/Die4Ever/build-engine-randomizer/files/10830300/eduke32.txt)

**Comment by Die4Ever** [comment]
maybe this is the issue?

```
 0.0712s INFO| Using directory E:/GOG Galaxy/Games/Duke Nukem 3D/
 0.0726s INFO| Using directory C:/eduke32/
```

I run with eDuke32.exe inside the game folder

**Comment by workdowg** [comment]
Yup! I moved eduke32.exe to the duke directory and now it is random!! Thanks. Adding that to the wiki and readme will help others also. Can't wait to play Blood like this!

**Comment by Die4Ever** [comment]
awesome thank you! I will also want to look into a solution for that, or maybe I should ask the eDuke32 guys if they can make this work better, it seems like they do intend that to work since you said it showed the Randomizer folder in the "Custom game content directory" list?

**Comment by workdowg** [comment]
Again, thanks for looking into this. And yes it does seem like their issue. They don't specify where to put their files. When I tried to copy it to the duke3d folder it wanted to overwrite some... But even without them it works fine....
