### ISSUE TITLE
Blood: Save not working with Randomizer

### ISSUE THREAD

**Issue by workdowg** [Die4Ever/build-engine-randomizer#31]
Again it is probably me setup.

The game randomizes fine but locks up when trying to save a game. I tried a stock (no custom folder) run using NBlood and was able to save a game. Next I tried a seed not using custom folder and killed my Blood install and NBlood install, doesn't finish loading. A new random game works using NBlood only but like I stated can't save, Stock DosBox loads also.

Let me know which files you might want to look at. Also a screenshot of the NBlood error when it locks up...

[nblood.log](https://github.com/Die4Ever/build-engine-randomizer/files/10843050/nblood.log)
[nblood.txt](https://github.com/Die4Ever/build-engine-randomizer/files/10843051/nblood.txt)
[nblood_cvars.txt](https://github.com/Die4Ever/build-engine-randomizer/files/10843052/nblood_cvars.txt)
[Randomizer.txt](https://github.com/Die4Ever/build-engine-randomizer/files/10843060/Randomizer.txt)

![Screenshot 2023-02-27 134752](https://user-images.githubusercontent.com/3537041/221656946-5b523a5c-f81f-4f59-8285-5bb693e658e5.png)

**Comment by Die4Ever** [comment]
hmm I can't reproduce your issue, also the nblood.log file is basically empty so maybe that's not the log file from the crash?

**Comment by workdowg** [comment]
Yeah, the crash only causes the error dialog, it never writes anything... Where do you keep Blood and NBlood on your system? Maybe it is like the same issue I had with Duke3D?

**Comment by Die4Ever** [comment]
I put nblood.exe inside the game folder like Duke, yeah

**Comment by workdowg** [comment]
Yup, same thing as Duke3D. It works this way. So just to be clear... People don't need to copy any files like the install instructions of NBlood say. Just copy the exe to the Blood directory. Thanks again for being on top of this!

**Comment by Die4Ever** [comment]
thank you for reporting bugs/issues! nobody has been reporting anything so it's hard to know the things that trip people up, I'm working on some things to make this a bit easier hopefully

**Comment by Die4Ever** [comment]
Would you be willing to test a beta version? This one creates a bat file to run more easily, makes packaging a bit neater, and does a better job of cleaning up its old files

[build-engine-randomizer.exe.zip](https://github.com/Die4Ever/build-engine-randomizer/files/10890875/build-engine-randomizer.exe.zip)
