### ISSUE TITLE
figure out Duke 3D swappable_items and swappable_enemies

### ISSUE THREAD

**Issue by Die4Ever** [Die4Ever/build-engine-randomizer#5]
C:/Games/Build Engine/Duke Nukem 3D/DUKE3D.GRP 22b6938fe767e5cc57d1fe13080cd522 detected game:  Duke Nukem 3D       

<details>

```
LOGO.ANM 1507336
CINEOV2.ANM 655497
CINEOV3.ANM 395044
RADLOGO.ANM 66162
DUKETEAM.ANM 66467
VOL41A.ANM 1810645
VOL42A.ANM 1113050
VOL43A.ANM 1831249
VOL4E1.ANM 517262
VOL4E2.ANM 1103718
VOL4E3.ANM 1365862
DEFS.CON 35992
GAME.CON 151190
USER.CON 45482
D3DTIMBR.TMB 3328
DUKE3D.BIN 4000
LOOKUP.DAT 10266
PALETTE.DAT 82690
TABLES.DAT 8448
FLYBY.VOC 37715
SECRET.VOC 21393
BLANK.VOC 34
ROAM06.VOC 11920
ROAM58.VOC 11795
PREDRG.VOC 11062
GBLASR01.VOC 5243
PREDPN.VOC 12518
PREDDY.VOC 8207
CHOKN12.VOC 23523
PREDRM.VOC 9664
LIZSPIT.VOC 10761
PIGRM.VOC 3881
ROAM29.VOC 13981
ROAM67.VOC 9180
PIGRG.VOC 21349
PIGPN.VOC 6030
PIGDY.VOC 12403
PIGWRN.VOC 35773
OCTARM.VOC 13536
OCTARG.VOC 8120
OCTAAT1.VOC 26749
OCTAAT2.VOC 5732
OCTAPN.VOC 14213
OCTADY.VOC 8343
BOS1RM.VOC 36836
BOS1RG.VOC 12864
BOS1PN.VOC 12518
BOS1DY.VOC 19473
KICKHIT.VOC 1806
RICOCHET.VOC 4683
BULITHIT.VOC 2170
PISTOL.VOC 3764
CLIPOUT.VOC 3909
CLIPIN.VOC 5613
CHAINGUN.VOC 3198
SHOTGNCK.VOC 7812
RPGFIRE.VOC 8256
BOMBEXPL.VOC 21020
PBOMBBNC.VOC 1360
WPNSEL21.VOC 5468
SHRINK.VOC 9381
LSRBMBPT.VOC 1926
LSRBMBWN.VOC 2618
SHRINKER.VOC 9701
VENTBUST.VOC 7522
GLASS.VOC 8674
GLASHEVY.VOC 8663
SHORTED.VOC 5840
SPLASH.VOC 13014
ALERT.VOC 3127
REACTOR.VOC 5575
SUBWAY.VOC 9453
GEARGRND.VOC 8697
GASP.VOC 9361
GASPS07.VOC 16215
PISSING.VOC 12180
KNUCKLE.VOC 1700
DRINK18.VOC 10767
EXERT.VOC 3895
HARTBEAT.VOC 4295
PAIN13.VOC 5686
PAIN28.VOC 4843
PAIN39.VOC 4796
PAIN87.VOC 2534
WETFEET.VOC 6652
LAND02.VOC 3139
DUCTWLK.VOC 2212
PAIN54.VOC 2568
PAIN75.VOC 4049
PAIN93.VOC 3712
PAIN68.VOC 4536
DAMN03.VOC 6782
DAMNIT04.VOC 5530
COMEON02.VOC 7031
WAITIN03.VOC 17544
COOL01.VOC 6298
AHMUCH03.VOC 22320
DANCE01.VOC 9644
LETSRK03.VOC 9430
READY2A.VOC 12741
RIPEM08.VOC 14287
ROCKIN02.VOC 8132
AHH04.VOC 10167
GULP01.VOC 2712
PAY02.VOC 34223
AMESS06.VOC 20280
BITCHN04.VOC 11125
DOOMED16.VOC 23392
HOLYCW01.VOC 12449
HOLYSH02.VOC 12495
IMGOOD12.VOC 15165
ONLYON03.VOC 16055
PIECE02.VOC 16373
RIDES09.VOC 14151
2RIDE06.VOC 36266
THSUK13A.VOC 18400
WANSOM4A.VOC 12800
MYSELF3A.VOC 22239
NEEDED03.VOC 16086
SHAKE2A.VOC 9819
DUKNUK14.VOC 37069
GETSOM1A.VOC 11775
GOTHRT01.VOC 21697
GROOVY02.VOC 8942
WHRSIT05.VOC 8231
BOOBY04.VOC 29614
DIESOB03.VOC 16365
DSCREM04.VOC 30563
LOOKIN01.VOC 17243
PISSIN01.VOC 12783
GETITM19.VOC 1961
SCUBA.VOC 16811
JETPAKON.VOC 9617
JETPAKI.VOC 7953
JETPAKOF.VOC 9980
GOGGLE12.VOC 1746
THUD.VOC 3842
SQUISH.VOC 10681
TELEPORT.VOC 5303
GBELEV01.VOC 14121
GBELEV02.VOC 2028
SWITCH.VOC 1824
FLUSH.VOC 29559
QUAKE.VOC 15175
MONITOR.VOC 1682
POOLBAL1.VOC 2036
ONBOARD.VOC 4960
BUBBLAMB.VOC 29114
MACHAMB.VOC 12735
WIND54.VOC 43594
STEAMHIS.VOC 8359
BARMUSIC.VOC 77801
WARAMB13.VOC 42180
WARAMB21.VOC 40927
WARAMB23.VOC 42467
WARAMB29.VOC 18103
COMPAMB.VOC 18209
SLIDOOR.VOC 13517
OPENDOOR.VOC 7097
EDOOR10.VOC 10969
EDOOR11.VOC 10784
FSCRM10.VOC 12070
H2OGRGL2.VOC 24238
GRIND.VOC 9276
ENGHUM.VOC 9630
LAVA06.VOC 26414
PHONBUSY.VOC 10853
ROAM22.VOC 30360
AMB81B.VOC 50616
ROAM98B.VOC 22046
H2ORUSH2.VOC 15647
PROJRUN.VOC 5697
FIRE09.VOC 38636
!PRISON.VOC 59851
!PIG.VOC 50626
!BOSS.VOC 45621
MICE3.VOC 15912
DRIP3.VOC 4124
ITEM15.VOC 1994
BONUS.VOC 274985
CATFIRE.VOC 11959
KILLME.VOC 24419
SHOTGUN7.VOC 52477
DMDEATH.VOC 10553
HAPPEN01.VOC 13719
DSCREM15.VOC 10642
DSCREM16.VOC 9677
DSCREM17.VOC 5529
DSCREM18.VOC 12210
DSCREM38.VOC 13499
RIP01.VOC 29210
NOBODY01.VOC 36937
CHEW05.VOC 52255
LETGOD01.VOC 16172
HAIL01.VOC 20214
BLOWIT01.VOC 22265
EATSHT01.VOC 25003
FACE01.VOC 36917
INHELL01.VOC 21017
SUKIT01.VOC 15327
PISSES01.VOC 27560
MUSTDIE.VOC 40373
DEFEATED.VOC 37429
MONOLITH.VOC 52923
HYDRO50.VOC 16495
ASWTCH23.VOC 4799
HYDRO22.VOC 14857
HYDRO24.VOC 21857
HYDRO27.VOC 22297
HYDRO34.VOC 16733
HYDRO40.VOC 22093
HYDRO43.VOC 23031
VAULT04.VOC 22013
2BWILD.VOC 153467
FREEZE.VOC 31461
B2ATK02.VOC 17491
B2ATK01.VOC 11655
B2DIE03.VOC 44797
B2PAIN03.VOC 11919
B2REC03.VOC 18307
B3ROAM01.VOC 22941
B3DIE03G.VOC 24101
B3REC03G.VOC 11333
B3PAIN04.VOC 21625
CTRLRM25.VOC 17741
HLIDLE03.VOC 16701
LIZSHIT3.VOC 4539
ADOOR1.VOC 21743
ADOOR2.VOC 21437
FORCE01.VOC 30756
JONES04.VOC 22448
QUAKE06.VOC 24110
TERMIN01.VOC 12115
BORN01.VOC 39923
CON03.VOC 26836
SNAKRM.VOC 43
SNAKRG.VOC 11967
SNAKATA.VOC 9017
SNAKATB.VOC 3261
SNAKPN.VOC 11803
SNAKDY.VOC 15896
COMMRM.VOC 12527
COMMRG.VOC 21769
COMMAT.VOC 21709
COMMPN.VOC 9783
COMMDY.VOC 26071
COMMSP.VOC 3830
SLIMAT.VOC 9871
SLHTCH01.VOC 12137
SLIDIE03.VOC 5569
SLIREC06.VOC 12819
SLIROA02.VOC 16099
KTITX.VOC 51836
WHIPYU01.VOC 29895
GUNHIT2.VOC 14711
HEADRIP3.VOC 76171
BUCKLE.VOC 20786
JETP2.VOC 4136
ZIPPER2.VOC 5637
NEWS.VOC 19197
WHISTLE.VOC 87627
CHEER.VOC 68525
GMEOVR05.VOC 9558
GRABBAG.VOC 307945
NAME01.VOC 15412
R&R01.VOC 36343
LANI08.VOC 26844
LANI05.VOC 23476
LANIDUK2.VOC 68419
TYPING.VOC 25814
CLANG1.VOC 4187
INTRO4H1.VOC 95868
INTRO4H2.VOC 169814
INTROA.VOC 13687
INTROB.VOC 19638
INTROC.VOC 16572
SQUISH1A.VOC 11839
SBR1C.VOC 15324
BANG1.VOC 19887
SKIDCR1.VOC 46976
MUZAK028.VOC 96135
MUZAKDIE.VOC 25468
ENLARGE.VOC 11748
DOM03.VOC 11847
DOM09.VOC 21728
DOM11.VOC 14171
DOM12.VOC 15178
DOLPHIN.VOC 6728
DEEPFRY1.VOC 30981
DOGWHINE.VOC 29271
DOGYELP.VOC 6944
SWEET03.VOC 7626
SWEET04.VOC 7719
SWEET05.VOC 14454
SWEET16.VOC 15646
TRUMBLE.VOC 68549
TCLAP2A.VOC 70189
ALARM1A.VOC 23588
RAIN3A.VOC 49447
JEEP2A.VOC 10445
CDOOR1B.VOC 12300
WAVE1A.VOC 53300
EXSHOT3B.VOC 6970
SHORN1.VOC 35003
SBELL1A.VOC 19251
GRUN.VOC 13123
BRUN.VOC 14808
GSCORE.VOC 16319
BSCORE.VOC 17604
TANK3A.VOC 12765
BLROAM2A.VOC 20550
BLREC4B.VOC 20336
BLRIP1A.VOC 6097
BLRIP1B.VOC 3547
BLSPIT1A.VOC 22379
BLPAIN1B.VOC 8225
BLDIE3A.VOC 16657
BQROAM2A.VOC 26563
BQREC2A.VOC 23306
BQPAIN2A.VOC 13268
BQSHOCK3.VOC 54390
BQEGG1A.VOC 29164
BQDIE1A.VOC 21138
ABORT01.VOC 27189
KICK01-I.VOC 18528
AISLE402.VOC 18616
ANNOY03.VOC 11488
BOOKEM03.VOC 13842
CRY01.VOC 14940
DETRUCT2.VOC 20641
EAT08.VOC 16334
ESCAPE01.VOC 19538
MAKEDAY1.VOC 20287
SOHELP02.VOC 12791
VACATN01.VOC 30572
YIPPIE01.VOC 18682
YOHOHO01.VOC 21654
YOHOHO09.VOC 37485
INDPNC01.VOC 17265
MDEVL01.VOC 22779
MEAT04-N.VOC 18681
PARTY03.VOC 28808
POSTAL01.VOC 19103
SMACK02.VOC 27296
VOCAL02.VOC 33003
BEBACK01.VOC 5862
GETCRAP1.VOC 14673
GUYSUK01.VOC 11389
SLACKER1.VOC 17782
GOAWAY.VOC 15239
GRABBAG.MID 14287
STALKER.MID 34703
DETHTOLL.MID 7185
STREETS.MID 52051
WATRWLD1.MID 25371
SNAKE1.MID 36088
THECALL.MID 16764
STORM.MID 39566
FATCMDR.MID 16530
GUTWRNCH.MID 45372
NAMES.MID 34022
GLOOMY.MID 12341
FUTURMIL.MID 49106
INTENTS.MID 14523
INVADER.MID 17106
SUBWAY.MID 14818
AHGEEZ.MID 41665
233C.MID 53029
ALFREDH.MID 7488
ALIENZ.MID 61838
GOTHAM.MID 43002
INHIDING.MID 49695
LORDOFLA.MID 39852
PIZZED.MID 16759
ROBOCREP.MID 12089
SPOOK.MID 12722
STALAG.MID 34931
URBAN.MID 29838
WHOMP.MID 15369
XPLASMA.MID 28903
BRIEFING.MID 8902
MISSIMP.MID 61627
WAREHAUS.MID 62150
BAKEDGDS.MID 15857
PREPD.MID 17969
CF.MID 30304
LEMCHILL.MID 34541
LAYERS.MID 12412
FLOGHORN.MID 4351
POB.MID 68585
DEPART.MID 39640
RESTRICT.MID 20825
TILES000.ART 1764538
TILES001.ART 1687911
TILES002.ART 847094
TILES003.ART 1113891
TILES004.ART 1147073
TILES005.ART 934595
TILES006.ART 587951
TILES007.ART 1054311
TILES008.ART 592057
TILES009.ART 1269998
TILES010.ART 2281496
TILES011.ART 57815
TILES012.ART 1060417
TILES013.ART 998283
TILES014.ART 6160
TILES015.ART 6160
TILES016.ART 1858901
TILES017.ART 722612
TILES018.ART 1490897
TILES019.ART 867463
E1L3.MAP 156698
E1L4.MAP 184166
E1L5.MAP 168514
E1L6.MAP 107222
E1L7.MAP 69030
E2L1.MAP 110898
E2L2.MAP 100622
E2L3.MAP 172262
E2L4.MAP 148110
E2L5.MAP 76270
E2L6.MAP 118910
E2L7.MAP 155398
E2L8.MAP 249582
E2L9.MAP 78458
E2L10.MAP 54134
E2L11.MAP 47526
E3L1.MAP 118478
E3L2.MAP 110290
E3L3.MAP 91862
E3L4.MAP 85898
E3L5.MAP 75022
E3L6.MAP 87270
E3L7.MAP 75290
E3L8.MAP 132426
E3L9.MAP 9070
E3L10.MAP 81718
E1L1.MAP 104562
```

</details>

**Comment by DuardusDuarnido** [comment]
> C:/Games/Build Engine/Duke Nukem 3D/DUKE3D.GRP 22b6938fe767e5cc57d1fe13080cd522 detected game:  Duke Nukem 3D       
> 
> <details>
> 
> ```
> LOGO.ANM 1507336
> CINEOV2.ANM 655497
> CINEOV3.ANM 395044
> RADLOGO.ANM 66162
> DUKETEAM.ANM 66467
> VOL41A.ANM 1810645
> VOL42A.ANM 1113050
> VOL43A.ANM 1831249
> VOL4E1.ANM 517262
> VOL4E2.ANM 1103718
> VOL4E3.ANM 1365862
> DEFS.CON 35992
> GAME.CON 151190
> USER.CON 45482
> D3DTIMBR.TMB 3328
> DUKE3D.BIN 4000
> LOOKUP.DAT 10266
> PALETTE.DAT 82690
> TABLES.DAT 8448
> FLYBY.VOC 37715
> SECRET.VOC 21393
> BLANK.VOC 34
> ROAM06.VOC 11920
> ROAM58.VOC 11795
> PREDRG.VOC 11062
> GBLASR01.VOC 5243
> PREDPN.VOC 12518
> PREDDY.VOC 8207
> CHOKN12.VOC 23523
> PREDRM.VOC 9664
> LIZSPIT.VOC 10761
> PIGRM.VOC 3881
> ROAM29.VOC 13981
> ROAM67.VOC 9180
> PIGRG.VOC 21349
> PIGPN.VOC 6030
> PIGDY.VOC 12403
> PIGWRN.VOC 35773
> OCTARM.VOC 13536
> OCTARG.VOC 8120
> OCTAAT1.VOC 26749
> OCTAAT2.VOC 5732
> OCTAPN.VOC 14213
> OCTADY.VOC 8343
> BOS1RM.VOC 36836
> BOS1RG.VOC 12864
> BOS1PN.VOC 12518
> BOS1DY.VOC 19473
> KICKHIT.VOC 1806
> RICOCHET.VOC 4683
> BULITHIT.VOC 2170
> PISTOL.VOC 3764
> CLIPOUT.VOC 3909
> CLIPIN.VOC 5613
> CHAINGUN.VOC 3198
> SHOTGNCK.VOC 7812
> RPGFIRE.VOC 8256
> BOMBEXPL.VOC 21020
> PBOMBBNC.VOC 1360
> WPNSEL21.VOC 5468
> SHRINK.VOC 9381
> LSRBMBPT.VOC 1926
> LSRBMBWN.VOC 2618
> SHRINKER.VOC 9701
> VENTBUST.VOC 7522
> GLASS.VOC 8674
> GLASHEVY.VOC 8663
> SHORTED.VOC 5840
> SPLASH.VOC 13014
> ALERT.VOC 3127
> REACTOR.VOC 5575
> SUBWAY.VOC 9453
> GEARGRND.VOC 8697
> GASP.VOC 9361
> GASPS07.VOC 16215
> PISSING.VOC 12180
> KNUCKLE.VOC 1700
> DRINK18.VOC 10767
> EXERT.VOC 3895
> HARTBEAT.VOC 4295
> PAIN13.VOC 5686
> PAIN28.VOC 4843
> PAIN39.VOC 4796
> PAIN87.VOC 2534
> WETFEET.VOC 6652
> LAND02.VOC 3139
> DUCTWLK.VOC 2212
> PAIN54.VOC 2568
> PAIN75.VOC 4049
> PAIN93.VOC 3712
> PAIN68.VOC 4536
> DAMN03.VOC 6782
> DAMNIT04.VOC 5530
> COMEON02.VOC 7031
> WAITIN03.VOC 17544
> COOL01.VOC 6298
> AHMUCH03.VOC 22320
> DANCE01.VOC 9644
> LETSRK03.VOC 9430
> READY2A.VOC 12741
> RIPEM08.VOC 14287
> ROCKIN02.VOC 8132
> AHH04.VOC 10167
> GULP01.VOC 2712
> PAY02.VOC 34223
> AMESS06.VOC 20280
> BITCHN04.VOC 11125
> DOOMED16.VOC 23392
> HOLYCW01.VOC 12449
> HOLYSH02.VOC 12495
> IMGOOD12.VOC 15165
> ONLYON03.VOC 16055
> PIECE02.VOC 16373
> RIDES09.VOC 14151
> 2RIDE06.VOC 36266
> THSUK13A.VOC 18400
> WANSOM4A.VOC 12800
> MYSELF3A.VOC 22239
> NEEDED03.VOC 16086
> SHAKE2A.VOC 9819
> DUKNUK14.VOC 37069
> GETSOM1A.VOC 11775
> GOTHRT01.VOC 21697
> GROOVY02.VOC 8942
> WHRSIT05.VOC 8231
> BOOBY04.VOC 29614
> DIESOB03.VOC 16365
> DSCREM04.VOC 30563
> LOOKIN01.VOC 17243
> PISSIN01.VOC 12783
> GETITM19.VOC 1961
> SCUBA.VOC 16811
> JETPAKON.VOC 9617
> JETPAKI.VOC 7953
> JETPAKOF.VOC 9980
> GOGGLE12.VOC 1746
> THUD.VOC 3842
> SQUISH.VOC 10681
> TELEPORT.VOC 5303
> GBELEV01.VOC 14121
> GBELEV02.VOC 2028
> SWITCH.VOC 1824
> FLUSH.VOC 29559
> QUAKE.VOC 15175
> MONITOR.VOC 1682
> POOLBAL1.VOC 2036
> ONBOARD.VOC 4960
> BUBBLAMB.VOC 29114
> MACHAMB.VOC 12735
> WIND54.VOC 43594
> STEAMHIS.VOC 8359
> BARMUSIC.VOC 77801
> WARAMB13.VOC 42180
> WARAMB21.VOC 40927
> WARAMB23.VOC 42467
> WARAMB29.VOC 18103
> COMPAMB.VOC 18209
> SLIDOOR.VOC 13517
> OPENDOOR.VOC 7097
> EDOOR10.VOC 10969
> EDOOR11.VOC 10784
> FSCRM10.VOC 12070
> H2OGRGL2.VOC 24238
> GRIND.VOC 9276
> ENGHUM.VOC 9630
> LAVA06.VOC 26414
> PHONBUSY.VOC 10853
> ROAM22.VOC 30360
> AMB81B.VOC 50616
> ROAM98B.VOC 22046
> H2ORUSH2.VOC 15647
> PROJRUN.VOC 5697
> FIRE09.VOC 38636
> !PRISON.VOC 59851
> !PIG.VOC 50626
> !BOSS.VOC 45621
> MICE3.VOC 15912
> DRIP3.VOC 4124
> ITEM15.VOC 1994
> BONUS.VOC 274985
> CATFIRE.VOC 11959
> KILLME.VOC 24419
> SHOTGUN7.VOC 52477
> DMDEATH.VOC 10553
> HAPPEN01.VOC 13719
> DSCREM15.VOC 10642
> DSCREM16.VOC 9677
> DSCREM17.VOC 5529
> DSCREM18.VOC 12210
> DSCREM38.VOC 13499
> RIP01.VOC 29210
> NOBODY01.VOC 36937
> CHEW05.VOC 52255
> LETGOD01.VOC 16172
> HAIL01.VOC 20214
> BLOWIT01.VOC 22265
> EATSHT01.VOC 25003
> FACE01.VOC 36917
> INHELL01.VOC 21017
> SUKIT01.VOC 15327
> PISSES01.VOC 27560
> MUSTDIE.VOC 40373
> DEFEATED.VOC 37429
> MONOLITH.VOC 52923
> HYDRO50.VOC 16495
> ASWTCH23.VOC 4799
> HYDRO22.VOC 14857
> HYDRO24.VOC 21857
> HYDRO27.VOC 22297
> HYDRO34.VOC 16733
> HYDRO40.VOC 22093
> HYDRO43.VOC 23031
> VAULT04.VOC 22013
> 2BWILD.VOC 153467
> FREEZE.VOC 31461
> B2ATK02.VOC 17491
> B2ATK01.VOC 11655
> B2DIE03.VOC 44797
> B2PAIN03.VOC 11919
> B2REC03.VOC 18307
> B3ROAM01.VOC 22941
> B3DIE03G.VOC 24101
> B3REC03G.VOC 11333
> B3PAIN04.VOC 21625
> CTRLRM25.VOC 17741
> HLIDLE03.VOC 16701
> LIZSHIT3.VOC 4539
> ADOOR1.VOC 21743
> ADOOR2.VOC 21437
> FORCE01.VOC 30756
> JONES04.VOC 22448
> QUAKE06.VOC 24110
> TERMIN01.VOC 12115
> BORN01.VOC 39923
> CON03.VOC 26836
> SNAKRM.VOC 43
> SNAKRG.VOC 11967
> SNAKATA.VOC 9017
> SNAKATB.VOC 3261
> SNAKPN.VOC 11803
> SNAKDY.VOC 15896
> COMMRM.VOC 12527
> COMMRG.VOC 21769
> COMMAT.VOC 21709
> COMMPN.VOC 9783
> COMMDY.VOC 26071
> COMMSP.VOC 3830
> SLIMAT.VOC 9871
> SLHTCH01.VOC 12137
> SLIDIE03.VOC 5569
> SLIREC06.VOC 12819
> SLIROA02.VOC 16099
> KTITX.VOC 51836
> WHIPYU01.VOC 29895
> GUNHIT2.VOC 14711
> HEADRIP3.VOC 76171
> BUCKLE.VOC 20786
> JETP2.VOC 4136
> ZIPPER2.VOC 5637
> NEWS.VOC 19197
> WHISTLE.VOC 87627
> CHEER.VOC 68525
> GMEOVR05.VOC 9558
> GRABBAG.VOC 307945
> NAME01.VOC 15412
> R&R01.VOC 36343
> LANI08.VOC 26844
> LANI05.VOC 23476
> LANIDUK2.VOC 68419
> TYPING.VOC 25814
> CLANG1.VOC 4187
> INTRO4H1.VOC 95868
> INTRO4H2.VOC 169814
> INTROA.VOC 13687
> INTROB.VOC 19638
> INTROC.VOC 16572
> SQUISH1A.VOC 11839
> SBR1C.VOC 15324
> BANG1.VOC 19887
> SKIDCR1.VOC 46976
> MUZAK028.VOC 96135
> MUZAKDIE.VOC 25468
> ENLARGE.VOC 11748
> DOM03.VOC 11847
> DOM09.VOC 21728
> DOM11.VOC 14171
> DOM12.VOC 15178
> DOLPHIN.VOC 6728
> DEEPFRY1.VOC 30981
> DOGWHINE.VOC 29271
> DOGYELP.VOC 6944
> SWEET03.VOC 7626
> SWEET04.VOC 7719
> SWEET05.VOC 14454
> SWEET16.VOC 15646
> TRUMBLE.VOC 68549
> TCLAP2A.VOC 70189
> ALARM1A.VOC 23588
> RAIN3A.VOC 49447
> JEEP2A.VOC 10445
> CDOOR1B.VOC 12300
> WAVE1A.VOC 53300
> EXSHOT3B.VOC 6970
> SHORN1.VOC 35003
> SBELL1A.VOC 19251
> GRUN.VOC 13123
> BRUN.VOC 14808
> GSCORE.VOC 16319
> BSCORE.VOC 17604
> TANK3A.VOC 12765
> BLROAM2A.VOC 20550
> BLREC4B.VOC 20336
> BLRIP1A.VOC 6097
> BLRIP1B.VOC 3547
> BLSPIT1A.VOC 22379
> BLPAIN1B.VOC 8225
> BLDIE3A.VOC 16657
> BQROAM2A.VOC 26563
> BQREC2A.VOC 23306
> BQPAIN2A.VOC 13268
> BQSHOCK3.VOC 54390
> BQEGG1A.VOC 29164
> BQDIE1A.VOC 21138
> ABORT01.VOC 27189
> KICK01-I.VOC 18528
> AISLE402.VOC 18616
> ANNOY03.VOC 11488
> BOOKEM03.VOC 13842
> CRY01.VOC 14940
> DETRUCT2.VOC 20641
> EAT08.VOC 16334
> ESCAPE01.VOC 19538
> MAKEDAY1.VOC 20287
> SOHELP02.VOC 12791
> VACATN01.VOC 30572
> YIPPIE01.VOC 18682
> YOHOHO01.VOC 21654
> YOHOHO09.VOC 37485
> INDPNC01.VOC 17265
> MDEVL01.VOC 22779
> MEAT04-N.VOC 18681
> PARTY03.VOC 28808
> POSTAL01.VOC 19103
> SMACK02.VOC 27296
> VOCAL02.VOC 33003
> BEBACK01.VOC 5862
> GETCRAP1.VOC 14673
> GUYSUK01.VOC 11389
> SLACKER1.VOC 17782
> GOAWAY.VOC 15239
> GRABBAG.MID 14287
> STALKER.MID 34703
> DETHTOLL.MID 7185
> STREETS.MID 52051
> WATRWLD1.MID 25371
> SNAKE1.MID 36088
> THECALL.MID 16764
> STORM.MID 39566
> FATCMDR.MID 16530
> GUTWRNCH.MID 45372
> NAMES.MID 34022
> GLOOMY.MID 12341
> FUTURMIL.MID 49106
> INTENTS.MID 14523
> INVADER.MID 17106
> SUBWAY.MID 14818
> AHGEEZ.MID 41665
> 233C.MID 53029
> ALFREDH.MID 7488
> ALIENZ.MID 61838
> GOTHAM.MID 43002
> INHIDING.MID 49695
> LORDOFLA.MID 39852
> PIZZED.MID 16759
> ROBOCREP.MID 12089
> SPOOK.MID 12722
> STALAG.MID 34931
> URBAN.MID 29838
> WHOMP.MID 15369
> XPLASMA.MID 28903
> BRIEFING.MID 8902
> MISSIMP.MID 61627
> WAREHAUS.MID 62150
> BAKEDGDS.MID 15857
> PREPD.MID 17969
> CF.MID 30304
> LEMCHILL.MID 34541
> LAYERS.MID 12412
> FLOGHORN.MID 4351
> POB.MID 68585
> DEPART.MID 39640
> RESTRICT.MID 20825
> TILES000.ART 1764538
> TILES001.ART 1687911
> TILES002.ART 847094
> TILES003.ART 1113891
> TILES004.ART 1147073
> TILES005.ART 934595
> TILES006.ART 587951
> TILES007.ART 1054311
> TILES008.ART 592057
> TILES009.ART 1269998
> TILES010.ART 2281496
> TILES011.ART 57815
> TILES012.ART 1060417
> TILES013.ART 998283
> TILES014.ART 6160
> TILES015.ART 6160
> TILES016.ART 1858901
> TILES017.ART 722612
> TILES018.ART 1490897
> TILES019.ART 867463
> E1L3.MAP 156698
> E1L4.MAP 184166
> E1L5.MAP 168514
> E1L6.MAP 107222
> E1L7.MAP 69030
> E2L1.MAP 110898
> E2L2.MAP 100622
> E2L3.MAP 172262
> E2L4.MAP 148110
> E2L5.MAP 76270
> E2L6.MAP 118910
> E2L7.MAP 155398
> E2L8.MAP 249582
> E2L9.MAP 78458
> E2L10.MAP 54134
> E2L11.MAP 47526
> E3L1.MAP 118478
> E3L2.MAP 110290
> E3L3.MAP 91862
> E3L4.MAP 85898
> E3L5.MAP 75022
> E3L6.MAP 87270
> E3L7.MAP 75290
> E3L8.MAP 132426
> E3L9.MAP 9070
> E3L10.MAP 81718
> E1L1.MAP 104562
> ```
> 
> </details>
>
